### PR TITLE
Softmax omp support

### PR DESCRIPTION
**Pull request by zhenlinluo**
@piiswrong , pls kindly review. This is significant patch to accelerate softmax when using MKL.

### CODE REVIEW

**Comment by sxjscience** [comment]
Looks good to me. May try to fix the lint.

**Comment by mli** [comment]
@tqchen i remember the reason why tianqi removed omp is because it uses all cpu resources, and may affect both read decode and distributed training performance? is there a better way to decided how to turn on omp?

**Comment by zhenlinluo** [comment]
So far, I use USE_MKL to decide if enable it or not. So far, I don't try to do distributed training with MKL enabled since it mainly target for inference yet. But in the future if we want to do distributed training, we can see what's the appropriate way. I don't know what is read decode. @mli can you explain a little bit?

**Comment by mli** [comment]
read images and do augmentation, it eats a lot of CPU resources

**Comment by zhenlinluo** [comment]
Okey, I can remove omp for mapplan func.

**Comment by zhenlinluo** [comment]
@tqchen @mli @sxjscience @piiswrong  Any update? The update is okey?

**Comment by sxjscience** [comment]
@zhenlinluo It's okay from my point of view. Because it only affects a small number of layers that uses reducing operators.

Also, how much will the code accelerate after applying this patch?

**Comment by zhenlinluo** [comment]
@sxjscience  Hi, for softmax layers, it depends on the CPU cores you have. For BDW 2S server with 44 cores, for RNN usage, it at least accelerate 10x from >500ms to <50ms for both fwd and bwd.

**Comment by zhenlinluo** [comment]
Any update? Can you merge it?

**Comment by tqchen** [comment]
Let us simply remove use mkl guard and enable openmp for softmax. However, let us be careful not to do so for map plan

**Comment by zhenlinluo** [comment]
@tqchen  Removed. pls check and merge

**Comment by tqchen** [comment]
What I mean is to remove the ifdef USE_MKL guard in the softmax(so it is enabled by default). after that, please do a squash and we can merge this in

**Comment by zhenlinluo** [comment]
@tqchen  just removed. pls let me know what else I need?

**Comment by tqchen** [comment]
thanks, this is merged

**Pull request merged**
