### PR TITLE
optimize reduce

### PR DESCRIPTION
**Pull request by piiswrong**
@tqchen 
reference:http://developer.download.nvidia.com/compute/cuda/1.1-Beta/x86_website/projects/reduction/doc/reduction.pdf

### CODE REVIEW

**Comment by tqchen** [comment]
This could cause overflow read because the tid guard is gone, and when buffer is not big enough.

**Comment by piiswrong** [comment]
buffer size is controlled by x_bits right?

**Comment by tqchen** [comment]
yes, say ```x_bits=4```, the reduction logic will also get executed for tid that is bigger than 16

**Comment by piiswrong** [comment]
it has to be bigger than a wrap

**Comment by tqchen** [comment]
The same function is used to do reduction for box, e.g. with each row smaller than a wrap
```
buf[16][16]
```

**Pull request closed without merging**
