### PR TITLE
fix bug of Softmax3DKernel for multiouput

### PR DESCRIPTION
**Pull request by tornadomeet**
when the number of multi-output label is larger than kBaseThreadNum(such as in segmentation, the number label is always larger than it),we should reuse the thread for computing in cuda kernel function, so it i think it is a bug.
ps:i used the SoftmaxOutput for multi-ouptpu these days(GPU) with mxnet and the weights are prone to be nan during training, when i fix this, it is correct for me.

### CODE REVIEW

**Comment by tqchen** [comment]
@piiswrong  Can you take a look?

**Comment by piiswrong** [comment]
LGTM

**Comment by tqchen** [comment]
remember to send a pr to mxnet to update submodule

**Comment by tornadomeet** [comment]
@tqchen @piiswrong  should i directly send a pr in mxnet side? i'm not familiar with the procedure how should send pr about the submodule of mxnet, just on the side of the mxnet or on the side of it's submodule side, e.g.mshaow, dmlc-core, ps-lite?

**Comment by tqchen** [comment]
Send the PR the mshadow, then do a pull in the mxnet, and send a PR to update the "pointer" to mshadow by using under mxnet/mshadow

```
git pull https://github.com/dmlc/mshadow master
```

**Comment by tornadomeet** [comment]
thanks~
because there is one pr (https://github.com/dmlc/mxnet/pull/741) i give last week has not been merged, it auto mergee into one pr.

**Pull request merged**
