### PR TITLE
fix a bug which causes reduce_with_axis to fail when reducing over the last axis

### PR DESCRIPTION
**Pull request by siemanko**
To reproduce the bug run the following code sample:

This should evaluate to all the values in the output being 4 (since we are reducing over the axis of size 4). However the value at index (1,2) is incorrect. 

``` cpp
typedef float T;
mshadow::Tensor<mshadow::cpu, 3, T> input_tensor(NULL, mshadow::Shape3(2,3,4));
mshadow::AllocSpace(&input_tensor);
input_tensor = 1;

mshadow::Tensor<mshadow::cpu, 2, T> reduced(NULL, mshadow::Shape2(2,3));
mshadow::AllocSpace(&reduced);
reduced = mshadow::expr::reduce_with_axis<mshadow::red::sum, false>(input_tensor, 0);

for(int i = 0; i < 2; ++i) {
    for (int j = 0; j < 3; ++j) {
        T v = reduced[i][j];
        std::cout << "reduced[" << i << "][" << j << "] = " << v << ";" << std::endl;
    }
}
```

### CODE REVIEW

**Comment by antinucleon** [comment]
@piiswrong

**Comment by sxjscience** [comment]
I can confirm that the bug exists. Running the code above and the result will be

```
reduced[0][0] = 4;
reduced[0][1] = 4;
reduced[0][2] = 4;
reduced[1][0] = 4;
reduced[1][1] = 4;
reduced[1][2] = 0;
```

Result will be correct after applying the PR.
Code:

``` c++
void test_reduce_error(){
  typedef float T;
  mshadow::Tensor<mshadow::cpu, 3, T> input_tensor(NULL, mshadow::Shape3(2, 3, 4));
  mshadow::AllocSpace(&input_tensor);
  input_tensor = 1;

  mshadow::Tensor<mshadow::cpu, 2, T> reduced(NULL, mshadow::Shape2(2, 3));
  mshadow::AllocSpace(&reduced);
  reduced = mshadow::expr::reduce_with_axis<mshadow::red::sum, false>(input_tensor, 2);

  for (int i = 0; i < 2; ++i) {
    for (int j = 0; j < 3; ++j) {
      T v = reduced[i][j];
      std::cout << "reduced[" << i << "][" << j << "] = " << v << ";" << std::endl;
    }
  }
}
int main(void) {
  test_reduce_error();
  return 0;
}
```

**Comment by piiswrong** [comment]
LGTM

**Comment by antinucleon** [comment]
@piiswrong Please update MXNet submodule.

**Pull request merged**
