### PR TITLE
Change index_t to int to fix OpenMP.

### PR DESCRIPTION
**Pull request by sxjscience**

### CODE REVIEW

**Comment by vchuravy** [comment]
Why is this failing with openmp?

**Comment by sxjscience** [comment]
@vchuravy I'm using VS2013 and its openmp only supports `int` variable for loop counter. http://stackoverflow.com/questions/2820621/why-arent-unsigned-openmp-index-variables-allowed

**Comment by tqchen** [comment]
a side note, have we bench-marked the perf when openmp turned on? It would be better to do such benchmark, since sometimes for small arrays, using openmp automatically do not speed things up

**Comment by tqchen** [comment]
OK, related to discussion in #97

**Pull request merged**
