### PR TITLE
Change names of mshadow's internal logger

### PR DESCRIPTION
**Pull request by jermainewang**
Since `mshadow` is a header library, I think it is a good idea to use different logging names (e.g. `MSHADOW_CHECK` instead of `CHECK`), especially when using it together with some customed logging headers whose names happen to be the same.

### CODE REVIEW

**Comment by piiswrong** [comment]
Why do we need separate logger?

**Comment by jermainewang** [comment]
In dmlc projects, No. But I am using it as my own project, which has my own logging system.

**Comment by tqchen** [comment]
please check the travis lint error, and squash your commits

**Comment by jermainewang** [comment]
@tqchen I am not sure how you guys squash commits in this situation? Since the commits have been pulled by several locals, will the squash affect them and create more commits?

**Comment by tqchen** [comment]
as long as they are all your commits, it should be fine. But be careful not to mess up with your local repos.

See http://mxnet.readthedocs.org/en/latest/contribute.html#how-to-combine-multiple-commits-into-one

This will allow you to combine the commits in your mshadow repo. In your local repo, though, git pull no longer works, because remote diverged. However, you can do a git reset --hard to reset them to the hash tag before all these commits, then git pull again. Remember to push in all your local changes first

**Comment by jermainewang** [comment]
Thanks! I've squashed commits till the one for merging upstream.

**Comment by tqchen** [comment]
please also do a consistent test with mxnet. I think in current logger it is muttually exclusive with DMLC's logging.h, which can cause problems(when dmlc/logging.h included first, MSHADOW_LOGGING can not be defined)

**Comment by jermainewang** [comment]
Fix the compatibility problem in ddbca68fe6f0f52b6cfc65f24d9beecb207a35c5. They are completely separate now and could be included in any order. Please have a look.

**Comment by tqchen** [comment]
One question, can we keep the DMLC namespace? SInce a lot of code in mxnet assumes catch dmlc::Error and changing the namespace will break such change.

**Comment by jermainewang** [comment]
Sorry for the delayed follow up. I don't have any good idea in mind. Do you have any suggestions? One way is to have mshadow::Error inherit dmlc::Error if defined. But this still needs correct order of header includes.

**Comment by tqchen** [comment]
Originally mshadow will avoid dmlc's logger simply by check DMLC_LOGGING macro. So it is likely that you can disable mshadow's logger definition by predefine DMLC_LOGGING, and keep everything in the old way

**Comment by tqchen** [comment]
closed for now

**Pull request closed without merging**
