### PR TITLE
add parallism in base map plan

### PR DESCRIPTION
**Pull request by xmchen1987**
add parallism in function MapPacketPlan, MapReduceKeepLowest and MapReduceKeepHighDim

### CODE REVIEW

**Comment by tqchen** [comment]
Openmp clause was removed because the parallelism do not make sense for some of the kernels, it is better to specify some of the parallelism manually through some options while keep most of them disabled

**Comment by tqchen** [comment]
@xmchen1987 Thanks for the PR, is it possible for us to check which of the kernels need parallelization? Manually turning  on all the CPU parallelization could throttle some of the use cases. Let us find a way to optionally turn on the openmp without turning everything on

**Comment by xmchen1987** [comment]
@tqchen  sure. we can start from operator +, if it is a big tensor, then it will need parallelization. currently you do not add parallelization for sse path(packet-inl).
BTW, can you list some of the cases CPU parallelization fail? I just can't image that.

**Comment by tqchen** [comment]
The main reason is that we might be running multiple cpu ops in pararallel via engine, so they compete with each other for resources for some reason.

**Comment by Darwin2011** [comment]
@tqchen @xmchen1987 
Could you give us some advice on this PR? Thanks.
 If multiple ops are on the fly, there's some resource competition. Sequential execution is also not one good way especially for multi-cores cpus.

**Pull request closed without merging**
