### PR TITLE
fix compile error with cudnn v4

### PR DESCRIPTION
**Pull request by yajiedesign**
fix compile error with cudnn v4
add cuda debug with debug

### CODE REVIEW

**Comment by sxjscience** [comment]
@yajiedesign I find that on Windows, I have to explicitly set the "-DNDEBUG=ON" to disable the debug mode here https://github.com/dmlc/mshadow/blob/master/cmake/Cuda.cmake#L172-L174. Have you met similar issues?

**Comment by sxjscience** [comment]
Also, after adding the `-G` flag, the `nosetests gpu/test_operator_gpu.py` will fail and the error message is  "too many resources requested for launch"

**Comment by yajiedesign** [comment]
@sxjscience the "NDEBUG" auto set with cmake when you chose release.

**Comment by sxjscience** [comment]
@yajiedesign Yes. It should set the flag. However I find that in the mxnet side the "NDEBUG" will be set, but not in the mshadow side.
My previous CMake command is like the following:
```
cmake -G "Visual Studio 14 2015 Win64" ^
-DCMAKE_BUILD_TYPE=Release ^
-DCMAKE_CONFIGURATION_TYPES="Release" ^
-DMKL_INCLUDE_DIR="C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2017\\windows\\mkl\\include" ^
-DMKL_RT_LIBRARY="C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2017\\windows\\mkl\\lib\\intel64\\mkl_rt.lib" ^
-DOpenCV_DIR="E:\ThirdParty\opencv-3.1\opencv\build\x64\vc14\lib" ^
-DCUDNN_INCLUDE="C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\include" ^
-DCUDNN_ROOT="C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\lib\\x64" ^
-DBLAS=MKL ..
```
I have to explicitly add the -DNDEBUG
```
cmake -G "Visual Studio 14 2015 Win64" ^
-DCMAKE_BUILD_TYPE=Release ^
-DCMAKE_CONFIGURATION_TYPES="Release" ^
-DMKL_INCLUDE_DIR="C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2017\\windows\\mkl\\include" ^
-DMKL_RT_LIBRARY="C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2017\\windows\\mkl\\lib\\intel64\\mkl_rt.lib" ^
-DOpenCV_DIR="E:\ThirdParty\opencv-3.1\opencv\build\x64\vc14\lib" ^
-DCUDNN_INCLUDE="C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\include" ^
-DCUDNN_ROOT="C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\lib\\x64" ^
-DNDEBUG=ON ^
-DBLAS=MKL ..
```

The version of my cmake is 3.3.1

**Comment by yajiedesign** [comment]
@sxjscience 
ok , 
`if(NOT NDEBUG)`
is not a good way.i am change it to `set CUDA_NVCC_FLAGS_DEBUG`
https://github.com/dmlc/mshadow/pull/198

**Pull request merged**
