### PR TITLE
Introduce CUDA 9 support in CMake

### PR DESCRIPTION
**Pull request by cbalioglu**
- Added `Volta` as a valid `CUDA_ARCH_NAME`.
- Added `Volta` to the list of known GPU architectures when used with `-DCUDA_ARCH_NAME=All`.
- Tested locally on V100, K80, and CPU-only boxes.

### CODE REVIEW

**Comment by goswamig** [comment]
Can we merge this change please ? 
@szha

**Comment by calumleslie** [comment]
Should "Volta" also be added to the __archs_names array? I think you won't be able to explicitly request it otherwise.

**Comment by calumleslie** [comment]
Also, and this is probably an MXNet bug rather than an MShadow one: The Cuda.cmake file is [included by MXNet](https://github.com/apache/incubator-mxnet/blob/master/CMakeLists.txt#L233), but MXNet's minimum CMake value is [set to 3.0.2](https://github.com/apache/incubator-mxnet/blob/master/CMakeLists.txt#L1). The GREATER_EQUAL operator used in this change was [added in 3.7](https://cmake.org/cmake/help/v3.7/release/3.7.html#commands) so this might break the build for MXNet users in a surprising way.

**Comment by anirudh2290** [comment]
@cbalioglu, Would you be able to address @calumleslie changes. Makes sense to add Volta to __arch_names. Also it would to use GREATER or EQUAL   so that it can be compatible with older versions of cmake. ` if(${CUDA_VERSION} GREATER 9.0 or ${CUDA_VERSION} EQUAL 9.0)`

**Comment by cbalioglu** [comment]
Updated.

**Pull request merged**
