### PR TITLE
[cuda] fix max grid for cuda > 6.0

### PR DESCRIPTION
**Pull request by antinucleon**

### CODE REVIEW

**Comment by asmushetzel** [comment]
Hi all, 
seems that this change will crash roi-pooling operator when incorporated into MxNet. Will try to fix it. It looks as if roi-pooling is taking this value as the maximum grid size in one dimension and then it fails in CheckLaunchParameters as there both dimensions are constrained to at most 2^16.

**Comment by asmushetzel** [comment]
The inconsistency is now that CheckLaunchParam has a hard check for each dimension at most 2^16-1 but there is no externally usable constant for an application supplied that reflects this number. Something like kMaxGridDim which then an operator can use in order to define proper x/y-grid dimensions. roi-pooling/bilinear-sampler/spatial-transformer just take kMaxGridNum as first grid dimension. They should use a constant as "kMaxGridDim" instead. 
I don't want to mess with this in mshadow, but dependent on it as I have pulled in a change on top of this PR and I need my change being reflected in MxNet, so I have to pull this PR also inr=to MxNet.
Any ideas from your side?

**Comment by piiswrong** [comment]
its usually not a good idea to have so many blocks any way since launching blocks has overhead. You should loop inside the kernel over grid size.

**Comment by asmushetzel** [comment]
Agreed. Just don't want to restructure existing other complex operators right now. Looking for a surgical fix such that we can at least retain the existing (working) behaviour.

**Comment by asmushetzel** [comment]
I can of course define a local constant in all 3 affected operators that will limit the grid dimensions to 2^16-1. That will work, but is ugly.

**Comment by asmushetzel** [comment]
Created PR 232 for mshadow. This supplies a constant for max grid size per dimension and uses this also in CheckLaunchParam. Using this constant, we can then easily fix the MxNet issues in above operators. Please review this PR.

**Comment by asmushetzel** [comment]
Created PR 5797 for MxNet which will bring in newest mshadow and corrects the affected operators. Please review.

**Pull request merged**
