### PR TITLE
fix sign compare warning

### PR DESCRIPTION
**Pull request by rahul003**
More changes to fix compilation warnings.
Reference: https://github.com/dmlc/mxnet/pull/7109

### CODE REVIEW

**Comment by tqchen** [comment]
please convert it to int, as -1 might be used as label(index_t is unsigned)

**Comment by rahul003** [comment]
If label can be negative, unsigned as is used currently would be wrong right?
Also, this means there can be a bug currently?  Ref: https://stackoverflow.com/a/5416724
I'll change them to int.

**Comment by tqchen** [comment]
@piiswrong

**Comment by cjolivier01** [comment]
shouldn't x be dim_t?  And this just cast x to long at compare time?

**Pull request merged**
