### PR TITLE
Re-Revert PR #348 to support large tensor size in MXNet

### PR DESCRIPTION
**Pull request by apeforest**
This PR is to patch a previous reverted PR #348 due to a build failure in MXNet.

This change is to fix the integer overflow issue in MXNet when a large tensor is created and converted to numpy. The related PR (https://github.com/apache/incubator-mxnet/pull/11742) in MXNet is pending this dependency to be merged.

### CODE REVIEW

**Comment by apeforest** [comment]
@tqchen @szha Patch the reverted PR #348 to fix large tensor overflow bug in MXNet

**Comment by szha** [comment]
Please open a PR in MXNet and show that this can be merged this without problems, w/ your fork of mshadow.

**Comment by apeforest** [comment]
@szha The PR in MXNet with this patch is also ready for review: https://github.com/apache/incubator-mxnet/pull/11742

Thanks!

Lin

**Comment by szha** [comment]
The downstream verification looks good to me. Thanks

**Pull request merged**
