### PR TITLE
check and close fp16 with arm

### PR DESCRIPTION
**Pull request by yajiedesign**

### CODE REVIEW

**Review by szha — APPROVED** [review]

**Comment by rahul003** [comment]
This should already be handled by Make and CMake. F16C will not be turned on for ARM builds. Did you run into some issue?

**Comment by yajiedesign** [comment]
yes.some issue.https://discuss.gluon.ai/t/topic/6100/7

**Comment by szha** [comment]
@tqchen

**Comment by rahul003** [comment]
Hello Sheng, this mostly wouldn't fix the issue faced by that user. If you look at the error log in that thread it has
`-DMSHADOW_USE_F16C=0`  which indicates that the makefile is already taking care of this, checking compiler and setting this flag is redundant.

**Comment by szha** [comment]
Thanks. Then the broken amalgamation is due to something else.

**Comment by rahul003** [comment]
Amalgamation isn't broken per se. It's tested in MXNet CI for both MIN=1 and MIN=0 flags.  I also see a new step for android on the CI.
Here's an example recent successful run on master
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1037/pipeline

There's something else about this user's environment.

**Comment by szha** [comment]
This code base has been donated to the Apache MXNet project per [#373](https://github.com/dmlc/mshadow/issues/373), and repo is deprecated. Future development should continue in Apache MXNet.

**Pull request closed without merging**
