### PR TITLE
Update mshadow.cmake to set BLAS

### PR DESCRIPTION
**Pull request by yinghu5**
Working with @yajiedesign, @TaoLv @pengzhao-intel @larroy @NeoZhangJiangyu to restructure the mxnet cmake build systems to make MKLDNN, MKL logic correct. 
In the past,  the logic to set  BLAS in mshadow.cmake is incorrect.  Now, USE_BLAS have high priority than USE_MKL_IF_AVAILABLE.

### CODE REVIEW

**Comment by pengzhao-intel** [comment]
Thanks of the improvement :) @larroy @szha 

Could you paste the diagram of `cmake` (you showed internally) so people can understand the change easily?

**Comment by pengzhao-intel** [comment]
BTW, how do you verify the current change? Could you paste the test results?

**Comment by yinghu5** [comment]
We planned to update the 3 cmakefiles :  ChooseBLAS.cmake, FindMKL.cmake and mshadow.cmake. the logic diagram is as the pdf.  Red parts are original logic  and green parts are new.   [cmake_mxnet_fixed.pdf](https://github.com/dmlc/mshadow/files/3125984/cmake_mxnet_fixed.pdf)
 
The mshadow.cmake part is as below. 
MKL_mxnet

**Comment by yinghu5** [comment]
we check the change by add debug message in cmakefile. 

message(STATUS "USE_MKL_IF_AVAILABLE ${USE_MKL_IF_AVAILABLE}")
message(STATUS "USE_MKLML_MKL ${USE_MKLML_MKL}")
message(STATUS "USE_MKLDNN ${USE_MKLDNN}")
message(STATUS "USE_BLAS ${USE_BLAS}")
message(STATUS "MKL_FOUND ${MKL_FOUND}")
message(STATUS "BLAS ${BLAS}")

and test were passed. Record into the  doc files. 
[cmake_test.docx](https://github.com/dmlc/mshadow/files/3126004/cmake_test.docx)

Thanks

**Comment by yinghu5** [comment]
@pengzhao-intel, please help to review the format change. thanks

**Review by pengzhao-intel — APPROVED** [review]
LGTM 

@szha @lebeg @larroy to review and merge.

**Comment by TaoLv** [comment]
@yinghu5 please use this upstream branch in your MXNet PR then we can have an end to end validation.

**Review by TaoLv — APPROVED** [review]

**Comment by TaoLv** [comment]
@yajiedesign @szha @eric-haibin-lin is it possible to have this merged?

**Review by larroy — APPROVED** [review]
LGTM

**Pull request merged**
