### PR TITLE
update to use MKLDNN option

### PR DESCRIPTION
**Pull request by jinhuang415**
MXNet has been moved to use MKLDNN instead of MKLML, so update the cmake option from USE_MKLML_MKL to USE_MKLDNN, for MXNet cmake options please refer to latest MXNet repo file CMakeLists.txt

This change is a followup for below MXNet issue, please help to merge this change to mshadow first and we can update MXNet side change later after this change:
https://github.com/apache/incubator-mxnet/issues/9868

### CODE REVIEW

**Comment by jinhuang415** [comment]
@pengzhao-intel  Add Patric

**Comment by jinhuang415** [comment]
@tqchen @piiswrong Would you help to review the PR in your proper time? Thanks.

**Comment by mike07026** [comment]
`mxnet_option(USE_MKLDNN           "Use MKLDNN variant of MKL (if MKL found)" ON IF USE_MKL_IF_AVAILABLE AND UNIX AND (NOT APPLE))`

Does it mean that MKLDNN option does not support windows platform yet ?

**Comment by mike07026** [comment]
`mxnet_option(USE_MKLDNN           "Use MKLDNN variant of MKL (if MKL found)" ON IF USE_MKL_IF_AVAILABLE AND UNIX AND (NOT APPLE))`

Does it mean that MKLDNN option does not support windows platform yet ?

**Comment by jinhuang415** [comment]
@mike07026 MKLDNN doesn't have such restriction and can support Linux/MAC/Windows all, I think this flag need to be changed to enable support for them

**Comment by szha** [comment]
This code base has been donated to the Apache MXNet project per [#373](https://github.com/dmlc/mshadow/issues/373), and repo is deprecated. Future development should continue in Apache MXNet.

**Pull request closed without merging**
