### PR TITLE
[Windows] make Packet::size constexpr

### PR DESCRIPTION
**Pull request by larroy**

### CODE REVIEW

**Comment by piiswrong** [comment]
why?

**Comment by larroy** [comment]
Compilation fails on windows vc 14 otherwise as linked from the other. Also it's better because is constexpr...

**Comment by cjolivier01** [comment]
This was done because of link errors cause by the constexpr static variable not being defined anywhere. I don’t see why compilation would fail on vc14.

**Comment by larroy** [comment]
Compilation failed because there was an array that used Packet::Size() to initialize the size in one of the tests, and this is not a constant expression which can be used to initialize an array. I was thinking of different strategies to fix it, and this one seemed the best solution as I saw that the packet size is a compile time constant, so no need to use the heap instead to allocate the array in the tests or anything else more complicated.

**Comment by cjolivier01** [comment]
This was done because of link errors cause by the constexpr static variable not being defined anywhere. It will be reintroduced. What do you suggest?

**Comment by larroy** [comment]
Just to clarify the background:

This changes a member function that is evaluated at runtime, to a constexpr which is known at compile time:

-  static inline index_t Size() { return 1; }
 +  static constexpr index_t size = 1;

The reason is this one:

in implicit_gemm.h we do this:

    const size_t packetSize = Packet::size;
    DType lhs_temp[packetSize], rhs_temp[packetSize];

If my memory doesn't fail me, variable length arrays are a C99 feature, most compilers now support it, but visual studio has been lagging on C99 features and focusing more in C++11 and beyond.  

I went back into the logs and I see you changed this from "  static const index_t kSize = 4;"    note that this was not a constexpr, so I don't expect linking problems in this case, as constexpr are inline. 

If a linking problem reappears, I will allocate the lhs_temp and rhs_temp arrays in the heap or with alloca. But do you think this problem can reappear with constexpr???  being constexpr there should not be any symbol defined, thus I don't see how there can be a link problem.

**Comment by cjolivier01** [comment]
Constexpr was tried there as well and is known to be problematic with some
versions of gcc. Just as we had a similar problem with Device::kGPU (or
whatever that constexpr in mshadow is that defines it) which was constexpr
and had to be changed to Context::kGPU which is an enum initialized to the
constexpr.

**Comment by larroy** [comment]
I think this is an interesting point, so I think we should test more versions of gcc to surface these problems in CI.   We can also revert the change and change the variable length arrays to be allocated in the heap or with alloca. Which one of the options would you be more favorable in your opinion?

**Comment by cjolivier01** [comment]
Is there any reason that the array can’t just be a vector in the test?

**Pull request merged**
