### PR TITLE
Enable null ptr in workspace for BatchGEMM

### PR DESCRIPTION
**Pull request by sxjscience**
@winstywang Just a temporary workout.
We can now use workspace with NULL ptr like the following: 

``` c++
mshadow::Tensor<xpu, 1, real_t*> workspace(NULL, mshadow::Shape1(3 * out.size(0)), s);
if (kNullOp != req) {
  mshadow::BatchGEMM<false, false>(out, mlhs, mrhs, 1.0f,
                                   (kAddTo == req) ? 1.0f : 0.0f,
                                   workspace);
}
```

### CODE REVIEW

**Comment by lyttonhao** [comment]
@sxjscience It seems that the code loses the definition of `alloc_workspace` around line 643.

**Comment by sxjscience** [comment]
@lyttonhao Yes, I've missed the definition. Will be revised soon.

**Comment by lyttonhao** [comment]
@sxjscience It works for me now. Thanks a lot!

**Comment by winstywang** [comment]
@sxjscience Let's update and merge it in

**Pull request merged**
